Repository="REPOSITORY-NAME";
Repo_PASSPHRASE="PASSWORD-BORG";

# Local Repository
Local=n
Local_Repo="/PATH/DIRECTORY/BORG/"${Repository};
Local_Back="/PAT/TO/BACKUP";
Local_Excl="*.log;*/log";
Local_OPT="";
Local_keep_hourly="";  # Number of hourly archives to keep
Local_keep_daily="";   # Number of daily archives to keep
Local_keep_weekly="";  # Number of weekly archives to keep
Local_keep_monthly=""; # Number of monthly archives to keep
Local_keep_yearly="";  # Number of yearly archives to keep

# Remote Repository
Remote=y
Remote_Repo="./PATH/TO/REMOTE/BACKUP/"${Repository};
Remote_Back=${Local_Back};
Remote_Excl=${Local_Excl};
Remote_OPT=""
Remote_keep_hourly="";  # Number of hourly archives to keep
Remote_keep_daily="";   # Number of daily archives to keep
Remote_keep_weekly="";  # Number of weekly archives to keep
Remote_keep_monthly=""; # Number of monthly archives to keep
Remote_keep_yearly="";  # Number of yearly archives to keep

SSH_USER="";            # SSH Username
SSH_PASS="";            # SSH Password (Optional if you use a certificate)
SSH_HOST="";            # SSH server
SSH_PORT="";            # SSH Port          Default: 22
SSH_CERT="";            # SSH Certificate

PRERUN="";
POSTRUN="";

Check=1                      # 0 = No check repo - 1 = Check & Backup - 2 = Check only
Prune=1                      # 0 = No prune - 1 = Prune before backup - 2 = Prune after backup

LCREATE_REPO=y;              # Create local repository if not exists?  Default: N
LCREATE_REPO_DIR=y;          # Create directory if not exists?         Default: N
RCREATE_REPO=Y;              # Create remote repository if not exists? Default: N
RCREATE_REPO_DIR=Y;          # Create directory if not exists?         Default: N
BORG_ENCRIPTION="";          # Encryption key mode                     Default: repokey-blake2
Borg_OPT="--exclude-caches"; # Opzioni globali per tutti i backup      Default: -None-
SHOWTEXT=Y                   # Mostra le informazioni del debug        Default: N
DEBUG=n                      # Debug - Will show clean password!       Default: N
DRYRUN=n                     # Dry run                                 Default: N

