Repository="REPOSITORY-NAME";
Repo_PASSPHRASE="PASSWORD-BORG";

BACKUP=y                # N = No backup     - Y = Run backup                                        Default: Y
CHECK=1                 # 0 = No check repo - 1 = Check   before backup - 2 = Check   after backup  Default: 0
PRUNE=1                 # 0 = No prune      - 1 = Prune   before backup - 2 = Prune   after backup  Default: 0
COMPACT=1               # 0 = No compact    - 1 = Compact before backup - 2 = Compact after backup  Default: 0

BACKUP_PATH="/PAT/TO/BACKUP";   # Path/files to backup, separate with ;
BACKUP_EXCL="*.log;*/log";      # Path/file to exclude, separate with ;

# Local Repository
LOCAL=n
Local_Repo="/PATH/DIRECTORY/BORG/"${Repository};

LOCAL_OPT="";          # Additional borg options
Local_keep_last=0;     # Keep the last N   archives - If > 0, other prune are ignored
Local_keep_hourly=0;   # Number of hourly  archives to keep
Local_keep_daily=0;    # Number of daily   archives to keep
Local_keep_weekly=0;   # Number of weekly  archives to keep
Local_keep_monthly=0;  # Number of monthly archives to keep
Local_keep_yearly=0;   # Number of yearly  archives to keep

# Remote Repository
REMOTE=y
Remote_Repo="./PATH/TO/REMOTE/BACKUP/"${Repository};

REMOTE_OPT="";         # Additional borg options
Remote_keep_last=0;    # Keep the last N   archives - If > 0, other prune are ignored
Remote_keep_hourly=0;  # Number of hourly  archives to keep
Remote_keep_daily=0;   # Number of daily   archives to keep
Remote_keep_weekly=0;  # Number of weekly  archives to keep
Remote_keep_monthly=0; # Number of monthly archives to keep
Remote_keep_yearly=0;  # Number of yearly  archives to keep

SSH_USER="";           # SSH Username
SSH_PASS="";           # SSH Password (Optional if you use a certificate)
SSH_HOST="";           # SSH server
SSH_PORT=22;           # SSH Port          Default: 22
SSH_CERT="";           # SSH Certificate

PRERUN="";             # Pre run commands/script
POSTRUN="";            # Post run commands/script

BORG_OPT="";           # Global additional borg options          Default:
BORG_ENCRIPTION="";    # Encryption key mode                     Default: repokey-blake2
LCREATE_REPO=y;        # Create local repository if not exists?  Default: N
LCREATE_REPO_DIR=y;    # Create directory if not exists?         Default: N
RCREATE_REPO=y;        # Create remote repository if not exists? Default: N
RCREATE_REPO_DIR=y;    # Create directory if not exists?         Default: N

SHOWTEXT=y             # Show log information                    Default: Y
DEBUG=n                # Debug - Will show clean password!       Default: N
DRYRUN=n               # Dry run                                 Default: N
