REPOSITORY="REPOSITORY-NAME";
REPO_PASSPHRASE="PASSWORD-BORG";

BACKUP=y                # N = No backup     - Y = Run backup                                        Default: Y
CHECK=0                 # 0 = No check repo - 1 = Check   before backup - 2 = Check   after backup  Default: 0
PRUNE=0                 # 0 = No prune      - 1 = Prune   before backup - 2 = Prune   after backup  Default: 0
COMPACT=0               # 0 = No compact    - 1 = Compact before backup - 2 = Compact after backup  Default: 0

BACKUP_PATH="/PATH/TO/BACKUP";   # Path/files to backup, separate with ;
BACKUP_EXCL="*.log;*/log";      # Path/file to exclude, separate with ;

# Local Repository
LOCAL=n
LOCAL_REPO="/PATH/DIRECTORY/BORG/"${REPOSITORY};

LOCAL_OPT="";          # Additional borg options
LOCAL_KEEP_LAST=0;     # Keep the last N   archives - If > 0, other prune are ignored  Default: 0
LOCAL_KEEP_HOURLY=0;   # Number of hourly  archives to keep  Default: 0
LOCAL_KEEP_DAILY=0;    # Number of daily   archives to keep  Default: 0
LOCAL_KEEP_WEEKLY=0;   # Number of weekly  archives to keep  Default: 0
LOCAL_KEEP_MONTHLY=0;  # Number of monthly archives to keep  Default: 0
LOCAL_KEEP_YEARLY=0;   # Number of yearly  archives to keep  Default: 0

# Remote Repository
REMOTE=y
REMOTE_REPO="./PATH/TO/REMOTE/BACKUP/"${REPOSITORY};

REMOTE_OPT="";         # Additional borg options
REMOTE_KEEP_LAST=0;    # Keep the last N   archives - If > 0, other prune are ignored   Default: 0
REMOTE_KEEP_HOURLY=0;  # Number of hourly  archives to keep  Default: 0
REMOTE_KEEP_DAILY=0;   # Number of daily   archives to keep  Default: 0
REMOTE_KEEP_WEEKLY=0;  # Number of weekly  archives to keep  Default: 0
REMOTE_KEEP_MONTHLY=0; # Number of monthly archives to keep  Default: 0
REMOTE_KEEP_YEARLY=0;  # Number of yearly  archives to keep  Default: 0

SSH_USER="";           # SSH Username
SSH_PASS="";           # SSH Password (Optional if you use a certificate)
SSH_HOST="";           # SSH server
SSH_PORT=22;           # SSH Port          Default: 22
SSH_CERT="";           # SSH Certificate

PRERUN="";             # Pre run commands/script
POSTRUN="";            # Post run commands/script

BORG_OPT="";           # Global additional borg options
BORG_ENCRIPTION="";    # Encryption key mode                     Default: repokey-blake2
LCREATE_REPO=y;        # Create local repository if not exists?  Default: Y 
LCREATE_REPO_DIR=y;    # Create directory if not exists?         Default: Y
RCREATE_REPO=y;        # Create remote repository if not exists? Default: Y
RCREATE_REPO_DIR=y;    # Create directory if not exists?         Default: Y

SHOWTEXT=y             # Show log information                    Default: Y
DEBUG=n                # Debug - Will show clean password!       Default: N
DRYRUN=n               # Dry run                                 Default: N
