REPOSITORY="REPOSITORY-NAME";
REPO_PASSPHRASE="PASSWORD-BORG";

REPO_PATH="/PATH/DIRECTORY/BORG/"${REPOSITORY};

# Path/files to backup, separate with ;
BACKUP_PATH="/PATH/TO/BACKUP";
# Path/file to exclude, separate with ;
BACKUP_EXCL="*.log;._*;sync.ffs_db;.apdisk;.DS_Store;.fseventsd;.keepThisDriveSpinning;.recycle;.TemporaryItems;.Trashes;*Recycle.Bin;desktop.ini;OneDriveTemp;RECYCLE*;Resources;System Volume Information;thumbs.db";

BACKUP=y           # N = No backup     - Y = Run backup                                        Default: Y
CHECK=0            # 0 = No check repo - 1 = Check   before backup - 2 = Check   after backup  Default: 0
PRUNE=0            # 0 = No prune      - 1 = Prune   before backup - 2 = Prune   after backup  Default: 0
COMPACT=0          # 0 = No compact    - 1 = Compact before backup - 2 = Compact after backup  Default: 0

KEEP_LAST=0        # Keep the last N   archives - If > 0, other prune are ignored  Default: 0
KEEP_HOURLY=0      # Number of hourly  archives to keep  Default: 0
KEEP_DAILY=0       # Number of daily   archives to keep  Default: 0
KEEP_WEEKLY=0      # Number of weekly  archives to keep  Default: 0
KEEP_MONTHLY=0     # Number of monthly archives to keep  Default: 0
KEEP_YEARLY=0      # Number of yearly  archives to keep  Default: 0

SSH_HOST=""        # SSH server if is set, backup become online backup
SSH_USER=""        # SSH Username
SSH_PASS=""        # SSH Password (Optional if you use a certificate)
SSH_PORT=22        # SSH Port          Default: 22
SSH_CERT=""        # SSH Certificate
SSH_OPT=""         # SSH Options                             Default: -o BatchMode=yes -o StrictHostKeyChecking=accept-new -o ConnectTimeout=5

PRERUN=""          # Pre run commands/script
POSTRUN=""         # Post run commands/script

BORG_OPT=""        # Global additional borg options
BORG_ENCRIPTION="" # Encryption key mode                     Default: repokey-blake2
DIR_CHECK=""       # Check if the path is a directoy         Default: stat --format=%F - Qnap: stat -c %F - *BSD / Hertzner: stat -f '%HT'
CREATE_REPO=y      # Create local repository if not exists?  Default: Y 
CREATE_REPO_DIR=y  # Create directory if not exists?         Default: Y

SHOWTEXT=y         # Show log information                    Default: Y
DEBUG=n            # Debug - Will show clean password!       Default: N
DRYRUN=n           # Dry run                                 Default: N


